# Generated by Django 5.1.4 on 2025-01-17 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecg', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='Patient',
        ),
    ]
